version: "3.9"

services:
  django:
    build: ./backend
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    container_name: "django"